JWTAthorizeTesting/Entities/Doctor.cs
using System.ComponentModel.DataAnnotations;

namespace JWTAthorizeTesting.Entities
{
    public class Doctor
    {
        public int Id { get; set; }

        public string FIO { get; set; }

        public ICollection<Specialization> Specializations { get; set; } = new List<Specialization>();// Specialization
        public ICollection<Polyclinic> Polyclinics { get; set; } = new List<Polyclinic>();
        public int? Price { get; set; }
        public string? Phone { get; set; }
        public string? Photo { get; set; }
        public string? ShortDesc { get; set; }
        public string? FullDesc { get; set; }

        //Experience
        public ICollection<Experience> Experience { get; set; } = new List<Experience>();
    }
}

JWTAthorizeTesting/Areas/Admins/Controllers/DataWorkerDocsController.cs
using JWTAthorizeTesting.Domain;
using JWTAthorizeTesting.Models;
using JWTAthorizeTesting.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using JWTAthorizeTesting.Services.Interfaces;

namespace JWTAthorizeTesting.Areas.Admins.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class DataWorkerDocsController : Controller
    {
        readonly IDocService _docService;
        private AppDbContext db;
        public DataWorkerDocsController(AppDbContext _db, IDocService docService)
        {
            db = _db;
            _docService = docService;
        }

        /// <summary>
        /// Выводим всех врачей в таблицу в админ панеле
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Doctors(int page = 1)
        {
            HttpContext.Session.Clear();
            ViewBag.SearchedDoc = null;

            var source = _docService.ChooseAll();

            int pageSize = 3;
            var count = source.Count();
            var items = source.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            DocViewModel docModel = new DocViewModel();
            docModel.pageViewModel = new PageViewModel(count, page, pageSize);
            docModel.Doctors = items;

            return View(docModel);
        }


        /// <summary>
        /// Редактируем определенного врача
        /// </summary>
        /// <param name="docId">передается через тег хелпер в представлении</param>
        /// <returns></returns>
        public async Task<IActionResult> EditDoc(int docId)
        {

            if (docId == 0)
            {
                return NotFound("Ошибка. Неверный ID.");
            }

            var doc = _docService.ChooseById(docId);

            if (doc == null)
            {
                return NotFound("Ошибка определения доктора. Объект пуст.");
            }

            DocViewModel docModel = new DocViewModel()
            {
                Id = doc.Id,
                FIO = doc.FIO,
                FullDesc = doc.FullDesc,
                ShortDesc = doc.ShortDesc,
                Phone = doc.Phone,
                Photo = doc.Photo,
                Price = doc.Price,
                OtherPolyclinics = _docService.ChooseOtherPoly(docId),
                OtherSpecializations = _docService.ChooseOtherSpec(docId),
                Polyclinics = doc.Polyclinics,
                Specializations = doc.Specializations
            };

            return View(docModel);
        }


        [HttpPost]
        public async Task<IActionResult> EditDoc(DocViewModel docModel)
        {

            var doc = new Doctor();
            doc.Id = docModel.Id;
            doc.FIO = docModel.FIO;
            doc.FullDesc = docModel.FullDesc;
            doc.ShortDesc = docModel.ShortDesc;
            doc.Price = docModel.Price;
            doc.Phone = docModel.Phone;

            if (!_docService.Update(doc,docModel.PhotoToUpload))
            {
                return NotFound("Ошибка редактирования");
            }

            return Redirect($"EditDoc?docId={docModel.Id}");
        }


        public async Task<IActionResult> AddDocInPoly(int polyId, int docId)
        {
            //Проверяемся на пустоту
            if (docId == 0 || docId == null || polyId == 0 || polyId == null)
            {
                return NotFound("Ошибка ID.");
            }

            if (!_docService.AddPoly(docId, polyId))
            {
                return NotFound("Ошибка добавления доктора в поликлинику.");
            }

            return Redirect($"EditDoc?docId={docId}");
        }


        public async Task<IActionResult> RemoveDocInPoly(int polyId, int docId)
        {

            //Проверяемся на пустоту
            if (docId == 0 || polyId == 0)
            {
                return NotFound("Ошибка ID.");
            }

            if (!_docService.RemovePoly(docId, polyId))
            {
                return NotFound("Ошибка удаления доктора в поликлинике");
            }

            return Redirect($"EditDoc?docId={docId}");
        }


        public async Task<IActionResult> RemoveDoc(int docId)
        {
            if (docId == 0)
            {
                return NotFound("Ошибка ID");
            }

            if (!_docService.Remove(docId))
            {
                return NotFound("Ошибка удаления врача.");
            }

            return RedirectToAction("SearchByTitle", "DataWorkerDocs");

        }


        [HttpGet]
        public IActionResult AddDoc()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> AddDoc(DocViewModel docModel)
        {
            if (docModel == null)
            {
                return NotFound("Ошибка добавления врача. Пустая модель.");
            }

            var doc = new Doctor();
            doc.Id = docModel.Id;
            doc.FIO = docModel.FIO;
            doc.FullDesc = docModel.FullDesc;
            doc.ShortDesc = docModel.ShortDesc;
            doc.Price = docModel.Price;
            doc.Phone = docModel.Phone;

            if (!_docService.Add(doc,docModel.PhotoToUpload))
            {
                return NotFound("Ошибка добавления врача. Возможно поле ФИО пустое или такой врач уже есть.");
            }

            return RedirectToAction("Doctors", "DataWorkerDocs");
        }


        public async Task<IActionResult> AddSpecToDoc(int specId, int docId)
        {
            if (specId == 0 || docId == 0)
            {
                return NotFound("Ошибка ID.");
            }

            if (!_docService.AddSpec(docId, specId))
            {
                return NotFound("Ошибка добавления специализации доктору.");
            }

            return Redirect($"EditDoc?docId={docId}");
        }


        public async Task<IActionResult> RemoveSpecInDoc(int specId, int docId)
        {
            if (specId == 0 || docId == 0)
            {
                return NotFound();
            }

            if (!_docService.RemoveSpec(docId, specId))
            {
                return NotFound("Ошибка удаления специализации у врача.");
            }
            return Redirect($"EditDoc?docId={docId}");

        }

        public IActionResult SearchByTitle(DocViewModel docModel, int page=1)
        {
            //Проверяю на пустоту название в моделе и пустоту сессии
            if (string.IsNullOrWhiteSpace(docModel.FIO) && !HttpContext.Session.Keys.Contains("searchDoc"))
            {
                return RedirectToAction("Doctors", "DataWorkerDocs");
            }

            //Если название из модели не пустое
            if (!string.IsNullOrWhiteSpace(docModel.FIO))
            {
                docModel.Doctors = _docService.ChooseForSearch(docModel.FIO);
            }
            //Если сессия содержит ключ
            if (HttpContext.Session.Keys.Contains("searchDoc"))
            {
                if (!string.IsNullOrWhiteSpace(docModel.FIO))
                {
                    HttpContext.Session.SetString("searchDoc", docModel.FIO);
                }

                //Выбираем для поиска по значению сессии
                docModel.Doctors= _docService.ChooseForSearch(HttpContext.Session.GetString("searchDoc"));
                ViewBag.SearchedDoc = HttpContext.Session.GetString("searchDoc");
            }
            //Если в сессии нет ключа 
            if (!HttpContext.Session.Keys.Contains("searchDoc"))
            {
                //Назначаем сессии значение из значения поиска
                HttpContext.Session.SetString("searchDoc", docModel.FIO);
                ViewBag.SearchedDoc = HttpContext.Session.GetString("searchDoc");
            }

            //Пагинация
            int pageSize = 3;
            var count = docModel.Doctors.Count();
            var items = docModel.Doctors.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            //В инкапсулированную модель нашей модель добавляем значения через конструктор
            docModel.pageViewModel = new PageViewModel(count, page, pageSize);
            docModel.Doctors = items;

            return View(docModel);
        }

        //Очистка поиска, чистим сессию и редирект на страницу городов
        public IActionResult ClearSearch()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Doctors", "DataWorkerDocs");

        }
    }
}

JWTAthorizeTesting/Controllers/DataWorkerController.cs
using JWTAthorizeTesting.Domain;
using JWTAthorizeTesting.Entities;
using JWTAthorizeTesting.Models;
using JWTAthorizeTesting.Models.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace JWTAthorizeTesting.Controllers
{

    [Authorize(Roles = "Administrator")]
    public class DataWorkerController: Controller
    {
        readonly ICityService _cityService;

        private AppDbContext db;
        public DataWorkerController(AppDbContext _db, ICityService cityService)
        {
            db = _db;
            _cityService = cityService;
        }


        /// <summary>
        /// Удаление поликлиники из города
        /// </summary>
        /// <param name="polyId"></param>
        /// <returns></returns>
        public IActionResult RemovePolyInCity(int? polyId,int? cityId)
        {
            //По polyId из представления ищем поликлинику из дбконтекста и назначаем внешн ключу
            //в таблице поликлиники значение null
            var poly = db.Polyclinics.FirstOrDefault(p => p.Id == polyId);
            if (poly == null)
            {
                return NotFound();
            }

            poly.CityId = null;


            db.SaveChanges();
            return Redirect($"EditCity?CityId={cityId}");

        }


        /// <summary>
        /// Отправляем HttpGet-запросом View Model.
        /// </summary>
        /// <param name="cityId"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> EditCity(int cityId)
        {
            if (cityId != null)
            {
                #region comment

                //   //Находим город по переданному cityId из представления
                //    City? city = await db.Cities.Include(c => c.Polyclinics)
                //        .FirstOrDefaultAsync(c => c.CityId == cityId);
                //    if (city != null)
                //    {
                //        //Создаем нашу view model
                //        AdminPanelViewModel adminModel = new AdminPanelViewModel();
                //        //Добавляем в неё найденный ранее город
                //        adminModel.Cities.Add(city);
                //        //Создаем список поликлиник для добавления в город, которые не присутствуют в этом городе
                //        List<Polyclinic> polyclinicsForAdding = await db.Polyclinics.Where(p => p.CityId != city.CityId).ToListAsync();
                //        //Добавляем этот список в нашу view model
                //        adminModel.Polyclinics.AddRange(polyclinicsForAdding);
                //        return View(adminModel);
                //    }
                #endregion

                City? city = _cityService.ChooseById(cityId);

                if (city == null)
                {
                    return NotFound("Неверный ID города, или города несуществует.");
                }

                var polyclinicsToAdd = _cityService.ChooseOtherPolyInCity(cityId);

                CityViewModel cityModel = new CityViewModel()
                {
                    CityId = cityId,
                    Title = city.Title,
                    OtherPolyclinics = polyclinicsToAdd,
                    PolyclinicsOfCity = city.Polyclinics.ToList()
                };

                return View(cityModel);
            }
            return NotFound();
        }


        /// <summary>
        /// Редактирование города
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> EditCity(CityViewModel cityModel)
        {
            if (!ModelState.IsValid)
            {
                return NotFound("Проверьте поля.");
            }

                if (!_cityService.Update(cityModel))
                {
                    return NotFound("Ошибка обновления.");
                }

                return Redirect($"EditCity?CityId={cityModel.CityId}");
            
        }


        /// <summary>
        /// Добавление поликлиники в город
        /// </summary>
        /// <param name="cityId">Передается из представления через тэг хелпер</param>
        /// <param name="polyId">Передается из представления через тэг хелпер</param>
        /// <returns></returns>
        public async Task<IActionResult> AddPolyInCity(int cityId,int polyId)
        {
           if (!_cityService.AddPolyclinic(cityId,polyId))
            {
                return NotFound("Ошибка добавления поликлиники в город");
            }

            return Redirect($"EditCity?CityId={cityId}");
        }


        /// <summary>
        /// Удаляем город из списка городов
        /// </summary>
        /// <param name="CityId">ID города, передается через представление</param>
        /// <returns></returns>
        public async Task<IActionResult> RemoveCity(int CityId)
        {
            if (!_cityService.Remove(CityId))
            {
                return NotFound("Ошибка удаления города.");
            }

            return RedirectToAction("AdminPanel", "Auth");

        }


        /// <summary>
        /// Добавление города, выводим представление добавления
        /// </summary>
        /// <returns></returns>
        public IActionResult AddCity()
        {
            return View();
        }


        /// <summary>
        /// Добавление города
        /// </summary>
        /// <param name="city">Город, передается через представление моделью</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> AddCity(CityViewModel cityModel)
        {
            //Проверяем на валидность, чтоб поле было заполнено
            if (!ModelState.IsValid)
            {
                return View(cityModel);
            }

            if (!_cityService.Add(cityModel))
            {
                return NotFound("Ошибка добавления. Возможно такой город уже существует.");
            }

            return RedirectToAction("AdminPanel", "Auth");
        }


    }
}

JWTAthorizeTesting/Areas/Admins/Views/DataWorkerDocs/AddDoc.cshtml
@model DocViewModel

<div class="container">
<h1>Админ. панель > Врачи > Добавление врача</h1>
<br /><br />


<a asp-action="Doctors" asp-controller="DataWorkerDocs">Вернуться ко списку врачей</a>
<br />

<form method="post" asp-action="AddDoc" asp-controller="DataWorkerDocs"  enctype="multipart/form-data">
    
        <label>Фото (Должно быть 300х300)</label> <br />
        <input class="btn btn-secondary" type="file" asp-for="@Model.PhotoToUpload" />
        <br/><br />

        
        <div class="col-md-3">
    <p>
        <label >ФИО врача</label> <br />
        
        <input type="text" class="form-control" class="form-control" asp-for="@Model.FIO" />
        
    </p>
    
        </div>
        
        <div class="col-md-3">
    <p>
        <label>Цена приема</label>
        <input type="text" class="form-control" class="form-control" asp-for="@Model.Price" />
    </p>
    
        </div>
        
        <div class="col-md-3">
    <p>
        <label>Телефон</label>
        <input type="text" class="form-control" class="form-control" asp-for="@Model.Phone" />
    </p>
    
        </div>
        
        <div class="col-md-7">
    <p>
        <label>Короткое описание</label>
        <textarea class="form-control"  asp-for="@Model.ShortDesc" ></textarea>
    </p>
    
        </div>
        
        <div class="col-md-7">
    <p>
        <label>Полное описание</label>
        <textarea  class="form-control" asp-for="@Model.FullDesc"> </textarea>
    </p>
    
        </div>
    <p>
        <input class="btn btn-primary" type="submit" value="Сохранить" />
    </p>
</form>
</div>

JWTAthorizeTesting/Areas/Admins/Views/DataWorkerDocs/Doctors.cshtml
@model DocViewModel

@await Html.PartialAsync("~/Areas/Admins/Views/Shared/_MenuForAdminPanel.cshtml")

<h1>Админ. панель > Врачи</h1>

<br /><br />


    <div class="container">
    <form class="d-flex" role="search" asp-action="SearchByTitle" asp-controller="DataWorkerDocs">
        <input asp-for="@Model.FIO" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>


<table class="table table-hover">
        <thead>
        <tr class="table-light"><th>Id</th><th>ФИО врача</th><th>Цена приема</th><th>Телефон</th><th>Фото</th><th>Короткое описание</th>
            <th >Полное описание</th><th>Специализации</th><th>Поликлиники</th>
            <td>
            <a asp-action="AddDoc" asp-controller="DataWorkerDocs"><b>Добавить врача</b></a>
            </td>
        </tr>
        </thead>
  <tbody class="table-group-divider">
            @foreach(var doc in Model.Doctors)
            {
               <tr class="table-light">
                <td>
                    @doc.Id
                </td>
                <td>
                    @doc.FIO
                </td>
                <td>
                    @doc.Price
                </td>
                <td>
                    @doc.Phone
                </td>
                <td class="col-md-2">
                    <img style="width:100%" src="@doc.Photo"/>
                </td>
                <td>
                    @doc.ShortDesc
                </td>
                <td>
                    @doc.FullDesc
                </td>
                <td>
                    @foreach(var spec in doc.Specializations)
                    {
                        <p>@spec.Title</p>
                    }
                </td>
                <td>
                    @foreach(var poly in doc.Polyclinics)
                    {
                        <p>@poly.Title</p>
                    }
                </td>
                <td><a asp-action="EditDoc" asp-controller="DataWorkerDocs" asp-route-docId="@doc.Id">Изменить</a></td>
                <td>
                <form method="post" asp-controller="DataWorkerDocs" asp-action="RemoveDoc"  asp-route-docId="@doc.Id">
                    <input type="submit" value="Удалить"/>
                </form>
                </td>
                </tr>
            }
        </table>

                        <br /><br /><br />

        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
        @if (Model.pageViewModel.HasPreviousPage)
        {
            <li class="page-item">
                <a class="page-link" asp-action="Doctors" asp-controller="DataWorkerDocs" asp-route-page="@(Model.pageViewModel.PageNumber - 1)">
                Назад
            </a>
            </li>
        }

        @for (int i = 1; i <= Model.pageViewModel.TotalPages; i++)
        {
            if (Model.pageViewModel.PageNumber == i)
            {
                <li class="page-item active"><a class="page-link" asp-action="Doctors" asp-controller="DataWorkerDocs" asp-route-page="@i">@i</a></li>
            }
            else
            {
                <li class="page-item"><a class="page-link" asp-action="Doctors" asp-controller="DataWorkerDocs" asp-route-page="@i">@i</a></li>  
            }
        }

        @if (Model.pageViewModel.HasNextPage)
        {
          <li class="page-item"><a class="page-link" asp-action="Doctors" asp-controller="DataWorkerDocs" asp-route-page="@(Model.pageViewModel.PageNumber + 1)">Вперед</a></li>
        }
          </ul>
        </nav>

JWTAthorizeTesting/Areas/Admins/Views/DataWorkerDocs/EditDoc.cshtml
@model DocViewModel

<div class="container">
<h1>Админ. панель > Врачи > Изменение врача @Model.FIO</h1>
<br /><br />

<a asp-action="Doctors" asp-controller="DataWorkerDocs">Вернуться ко списку врачей</a>
<br />


<form method="post" asp-action="EditDoc" asp-controller="DataWorkerDocs"  enctype="multipart/form-data">
    
        <label >Фото (Должно быть 300х300)</label> <br />
        <img class="col-md-5" src="@Model.Photo" /> <br />
        <input class="btn btn-secondary" type="file" asp-for="@Model.PhotoToUpload" />
        <br/><br />
        
        <div class="col-md-3">
    <p>
        <label>Идентификатор врача</label><br />
        <input type="text"  class="form-control" readonly asp-for="@Model.Id" /><br />
    </p>
    </div>

    
        <div class="col-md-3">
    <p>
        <label >ФИО врача</label> <br />
        
        <input type="text" class="form-control" asp-for="@Model.FIO" />
        </div>
    </p>
    
    
        <div class="col-md-3">
    <p>
        <label>Цена</label>
        <input type="text" class="form-control" asp-for="@Model.Price" />
        </div>
    </p>
    
    
        <div class="col-md-3">
    <p>
        <label>Телефон</label>
        <input type="text" class="form-control" asp-for="@Model.Phone" />
        </div>
    </p>
    
        <div class="col-md-7">
    <p>
        <label>Короткое описание</label>
        <textarea type="text" class="form-control" asp-for="@Model.ShortDesc"></textarea>
    </p>
    </div>
    
        <div class="col-md-7">
    <p>
        <label>Полное описание</label>
        <textarea type="text" class="form-control" asp-for="@Model.FullDesc" ></textarea>
     </p>
     </div>

      <p>
        <label>Специализации</label>
        <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Добавить специализацию
  </button>
        <ul class="dropdown-menu">
      @foreach(var specToAdd in Model.OtherSpecializations)
      {
        <li><a class="dropdown-item" asp-action="AddSpecToDoc" asp-controller="DataWorkerDocs" asp-route-specId="@specToAdd.SpecializationId" asp-route-docId="@Model.Id">@specToAdd.Title</a></li>
      }
        </ul>
        </div>


         <table class="table table-hover">
            @foreach(var spec in Model.Specializations)
            {
                <tr>
                    <td>
                        @spec.Title
                    </td>
                    <td>
                        <a asp-controller="DataWorkerDocs" asp-action="RemoveSpecInDoc" asp-route-specId="@spec.SpecializationId" asp-route-docId="@Model.Id">Удалить</a>
                    </td>
                </tr>
            }
        </table>
    </p>


     <p>
        <label>Поликлиники</label>
        <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Добавить поликлинику
  </button>
        <ul class="dropdown-menu">
      @foreach(var polyToAdd in Model.OtherPolyclinics)
      {
        <li><a class="dropdown-item" asp-action="AddDocInPoly" asp-controller="DataWorkerDocs" asp-route-polyId="@polyToAdd.Id" asp-route-docId="@Model.Id">@polyToAdd.Title</a></li>
      }
        </ul>
        </div>


         <table class="table table-hover">
            @foreach(var poly in Model.Polyclinics)
            {
                <tr>
                    <td>
                        @poly.Title
                    </td>
                    <td>
                        <a asp-controller="DataWorkerDocs" asp-action="RemoveDocInPoly" asp-route-polyId="@poly.Id" asp-route-docId="@Model.Id">Удалить</a>
                    </td>
                </tr>
            }
        </table>
    </p>
    
    <p>
        <input type="submit" class="btn btn-primary" value="Сохранить" />
    </p>
</form>

            </div>

JWTAthorizeTesting/Areas/Admins/Views/DataWorkerDocs/SearchByTitle.cshtml
@model DocViewModel

@await Html.PartialAsync("~/Areas/Admins/Views/Shared/_MenuForAdminPanel.cshtml")

<h1>Админ. панель > Врачи</h1>

<br /><br />


     <div class="container">
        <div class="d-flex">
        <h4>Поиск по значению: @ViewBag.SearchedDoc</h4>

    @if (ViewBag.SearchedDoc != null)
    {
        <a style="margin-left: 10px" class="btn btn-outline-success" asp-action="ClearSearch" asp-controller="DataWorkerDocs"> Очистить</a>
    }
    else
    {
    <form class="d-flex" role="search" asp-action="SearchByTitle" asp-controller="DataWorker">
        <input asp-for="@Model.FIO" class="form-control me-2" type="search" placeholder="Search" aria-label="Search" value="@ViewBag.SearchedDoc">
        <button class="btn btn-outline-success" type="submit">Search</button>
        <a class="btn btn-outline-success" asp-action="ClearSearch" asp-controller="DataWorkerDocs"> Очистить</a>
      </form>
    }
    </div>
    </div>


<table class="table table-hover">
        <thead>
        <tr class="table-light"><th>Id</th><th>ФИО врача</th><th>Цена приема</th><th>Телефон</th><th>Фото</th><th>Короткое описание</th>
            <th >Полное описание</th><th>Специализации</th><th>Поликлиники</th>
            <td>
            <a asp-action="AddDoc" asp-controller="DataWorkerDocs"><b>Добавить врача</b></a>
            </td>
        </tr>
        </thead>
  <tbody class="table-group-divider">
            @foreach(var doc in Model.Doctors)
            {
               <tr class="table-light">
                <td>
                    @doc.Id
                </td>
                <td>
                    @doc.FIO
                </td>
                <td>
                    @doc.Price
                </td>
                <td>
                    @doc.Phone
                </td>
                <td class="col-md-2">
                    <img style="width:100%" src="@doc.Photo"/>
                </td>
                <td>
                    @doc.ShortDesc
                </td>
                <td>
                    @doc.FullDesc
                </td>
                <td>
                    @foreach(var spec in doc.Specializations)
                    {
                        <p>@spec.Title</p>
                    }
                </td>
                <td>
                    @foreach(var poly in doc.Polyclinics)
                    {
                        <p>@poly.Title</p>
                    }
                </td>
                <td><a asp-action="EditDoc" asp-controller="DataWorkerDocs" asp-route-docId="@doc.Id">Изменить</a></td>
                <td>
                <form method="post" asp-controller="DataWorkerDocs" asp-action="RemoveDoc"  asp-route-docId="@doc.Id">
                    <input type="submit" value="Удалить"/>
                </form>
                </td>
                </tr>
            }
        </table>
        
        <br /><br /><br />


        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
        @if (Model.pageViewModel.HasPreviousPage)
        {
            <li class="page-item">
                <a class="page-link" asp-action="SearchByTitle" asp-controller="DataWorkerDocs" asp-route-page="@(Model.pageViewModel.PageNumber - 1)">
                Назад
            </a>
            </li>
        }

        @for (int i = 1; i <= Model.pageViewModel.TotalPages; i++)
        {
            if (Model.pageViewModel.PageNumber == i)
            {
                <li class="page-item active"><a class="page-link" asp-action="SearchByTitle" asp-controller="DataWorkerDocs" asp-route-page="@i">@i</a></li>
            }
            else
            {
                <li class="page-item"><a class="page-link" asp-action="SearchByTitle" asp-controller="DataWorkerDocs" asp-route-page="@i">@i</a></li>  
            }
        }

        @if (Model.pageViewModel.HasNextPage)
        {
          <li class="page-item"><a class="page-link" asp-action="SearchByTitle" asp-controller="DataWorkerDocs" asp-route-page="@(Model.pageViewModel.PageNumber + 1)">Вперед</a></li>
        }
          </ul>
        </nav>